// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcp0lY1yzjPRQsJvZUg-InrQHe2QsgqEE',
    appId: '1:120179228869:android:05599ec4286048d2ec70ac',
    messagingSenderId: '120179228869',
    projectId: 'fusshn-aef8e',
    storageBucket: 'fusshn-aef8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfCU8nmkTBByKczTuh3A0jNLWApBp9740',
    appId: '1:120179228869:ios:5e0e724ff6f67565ec70ac',
    messagingSenderId: '120179228869',
    projectId: 'fusshn-aef8e',
    storageBucket: 'fusshn-aef8e.appspot.com',
    iosBundleId: 'com.fusshn.fusshncustomer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAB7-M3vwxNdH-FadIdVj_LhNNGwpQZa38",
    authDomain: "fusshn-aef8e.firebaseapp.com",
    projectId: "fusshn-aef8e",
    storageBucket: "fusshn-aef8e.appspot.com",
    messagingSenderId: "120179228869",
    appId: "1:120179228869:web:cb0494dfc4a159dfec70ac",
    measurementId: "G-NQ3FFPD2T5",
  );
}
