List<PopularCitiesData> popularIndianCities = [
  const PopularCitiesData(
    name: "Mumbai",
    icon: 'mumbai_logo',
  ),
  const PopularCitiesData(
    name: "Hyderabad",
    icon: 'hyderabad_logo',
  ),
  const PopularCitiesData(
    name: "Ahmedabad",
    icon: 'ahmedabad_logo',
  ),
  const PopularCitiesData(
    name: "Delhi NCR",
    icon: 'delhi_ncr_logo',
  ),
  const PopularCitiesData(
    name: "Chennai",
    icon: 'chennai_logo',
  ),
  const PopularCitiesData(
    name: "Agra",
    icon: 'agra_logo',
  ),
  const PopularCitiesData(
    name: "Bengaluru",
    icon: 'mumbai_logo',
  ),
  const PopularCitiesData(
    name: "Chandigarh",
    icon: 'mumbai_logo',
  ),
  const PopularCitiesData(
    name: "Pune",
    icon: 'mumbai_logo',
  ),
  const PopularCitiesData(
    name: "Kolkata",
    icon: 'mumbai_logo',
  ),
];

class PopularCitiesData {
  final String name;
  final String icon;

  const PopularCitiesData({
    required this.name,
    required this.icon,
  });
}

List<String> allIndianCities = const [
  "Agra",
  "Ahmedabad",
  "Allahabad",
  "Amritsar",
  "Aurangabad",
  "Bengaluru",
  "Bareilly",
  "Bhopal",
  "Bhubaneswar",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Durgapur",
  "Faridabad",
  "Ghaziabad",
  "Gorakhpur",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Hubli",
  "Hyderabad",
  "Indore",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamshedpur",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolkata",
  "Kota",
  "Kozhikode",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangalore",
  "Meerut",
  "Mumbai",
  "Mysore",
  "Nagpur",
  "Nashik",
  "Noida",
  "Patna",
  "Pondicherry",
  "Pune",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Rourkela",
  "Salem",
  "Siliguri",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Udaipur",
  "Ujjain",
  "Vadodara",
  "Varanasi",
  "Vellore",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];
